// src/App.jsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import Header from './Header.jsx'
import Footer from './Footer.jsx'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
		<div id="pda">
			<div id="screen">
				<Header />
				{/* <RouterView :key="$route.path" @toggleItem="toggleItem" :itemsData="itemsData" /> */}
			</div>
		</div>
		<Footer />
		<div id="bkg"></div>
    </>
  )
}

export default App

// src/App.vue
<script>
import { RouterLink, RouterView } from 'vue-router'
import TheHeader from './components/TheHeader.vue'
// import TheFooter from './components/TheFooter.vue'
import itemsData from '@/assets/data/items.json'

export default {
	components: {
		TheHeader,
		// TheFooter
	}
}
</script>

<template>
	<div id="pda">
		<div id="screen">
			<TheHeader />
			<RouterView :key="$route.path" />
			<!-- <TheFooter /> -->
		</div>
	</div>
	<h1 id="title"><span>SUB</span>NAUTICA PDA</h1>
	<div id="bkg"></div>
</template>

<style></style>
