// src/views/NotesView.vue
<script>
import { RouterLink } from 'vue-router'

export default {
	data() {
		return {
			notes: ""
		}
	},
}
</script>

<template>
	<!-- HEADING -->
	<div id="heading">
		<h2>Notes</h2>
	</div>
	<!-- PANES -->
	<div id="panes">
		<div class="pane" id="notes-pane">
			<textarea v-model="notes" placeholder="Keep your notes here."></textarea>
		</div>
	</div>
</template>

<style>

</style>

// src/NotesView.jsx
import { useState } from 'react';

// export default {
// 	data() {
// 		return {
// 			notes: ""
// 		}
// 	},
// }

function NotesView() {
	const [count, setCount] = useState(0);

	return (
		<>
			<div className="pane" id="notes-pane">
				<textarea v-model="notes" placeholder="Keep your notes here."></textarea>
			</div>
		</>
	)
}

export default NotesView;
